define([], function () {
    return [
        { name: 'ABRAHAM', addressSystem: 'DELTA', priority: 0 },
        { name: 'ACORD LAKES', addressSystem: 'ACORD LAKES', priority: 0 },
        { name: 'ADAMSVILLE', addressSystem: 'BEAVER', priority: 0 },
        { name: 'ALPINE', addressSystem: 'ALPINE', priority: 1 },
        { name: 'ALPINE', addressSystem: 'PROVO', priority: 0 },
        { name: 'ALTA', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'ALTAMONT', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'ALTON', addressSystem: 'ALTON', priority: 3 },
        { name: 'ALTONAH', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'AM FORK', addressSystem: 'AMERICAN FORK', priority: 0 },
        { name: 'AMALGA', addressSystem: 'LOGAN', priority: 0 },
        { name: 'AMERICAN FK', addressSystem: 'AMERICAN FORK', priority: 2 },
        { name: 'AMERICAN FK', addressSystem: 'PROVO', priority: 0 },
        { name: 'AMERICAN FORK', addressSystem: 'AMERICAN FORK', priority: 3 },
        { name: 'AMERICAN FORK', addressSystem: 'PROVO', priority: 1 },
        { name: 'ANETH', addressSystem: 'BLANDING', priority: 0 },
        { name: 'ANGLE', addressSystem: 'ANGLE', priority: 0 },
        { name: 'ANNABELLA', addressSystem: 'ANNABELLA', priority: 0 },
        { name: 'ANTIMONY', addressSystem: 'ANTIMONY', priority: 0 },
        { name: 'APPLE VALLEY', addressSystem: 'APPLE VALLEY', priority: 0 },
        { name: 'ARAGONITE', addressSystem: 'TOOELE', priority: 0 },
        { name: 'ARCADIA', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'ARCHES', addressSystem: 'MOAB', priority: 0 },
        { name: 'AURORA', addressSystem: 'AURORA', priority: 0 },
        { name: 'AUSTIN', addressSystem: 'ELSINORE', priority: 0 },
        { name: 'AVALON', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'AVON', addressSystem: 'LOGAN', priority: 0 },
        { name: 'AXTELL', addressSystem: 'AXTELL', priority: 1 },
        { name: 'AXTELL', addressSystem: 'MANTI', priority: 0 },
        { name: 'BACCHUS', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'BALLARD', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'BAUER', addressSystem: 'TOOELE', priority: 0 },
        { name: 'BCC', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'BEAR RIVER CITY', addressSystem: 'BRIGHAM CITY', priority: 1 },
        { name: 'BEAR RIVER CY', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'BEAVER', addressSystem: 'BEAVER', priority: 0 },
        { name: 'BEAVER COUNTY', addressSystem: 'BEAVER', priority: 0 },
        { name: 'BEAVER DAM', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'BEAVER MOUNTAIN', addressSystem: 'LOGAN', priority: 1 },
        { name: 'BEAVER MTN', addressSystem: 'LOGAN', priority: 0 },
        { name: 'BENJAMIN', addressSystem: 'PROVO', priority: 0 },
        { name: 'BENNETT', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'BENSON', addressSystem: 'LOGAN', priority: 0 },
        { name: 'BERYL', addressSystem: 'BERYL', priority: 0 },
        { name: 'BERYL JCT', addressSystem: 'BERYL', priority: 0 },
        { name: 'BERYL JUNCTION', addressSystem: 'BERYL', priority: 1 },
        { name: 'BICKNELL', addressSystem: 'BICKNELL', priority: 0 },
        { name: 'BIG COTTONWOOD CANYON', addressSystem: 'SALT LAKE CITY', priority: 3 },
        { name: 'BIG COTTONWOOD CANYON RESORTS', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'BIG COTTONWOOD CYN', addressSystem: 'SALT LAKE CITY', priority: 2 },
        { name: 'BIG WATER', addressSystem: 'BIG WATER', priority: 0 },
        { name: 'BINGHAM CANYON', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'BINGHAM CYN', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'BIRCH CREEK', addressSystem: 'BIRCH CREEK', priority: 0 },
        { name: 'BIRDSEYE', addressSystem: 'PROVO', priority: 0 },
        { name: 'BLACK ROCK', addressSystem: 'FILLMORE', priority: 0 },
        { name: 'BLANDING', addressSystem: 'BLANDING', priority: 0 },
        { name: 'BLOOMINGTON', addressSystem: 'ST GEORGE', priority: 0 },
        { name: 'BLOOMINGTON HILLS', addressSystem: 'ST GEORGE', priority: 0 },
        { name: 'BLUE CREEK', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'BLUEBELL', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'BLUFF', addressSystem: 'BLUFF', priority: 0 },
        { name: 'BLUFFDALE', addressSystem: 'PROVO', priority: 0 },
        { name: 'BLUFFDALE', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'BONANZA', addressSystem: 'VERNAL', priority: 0 },
        { name: 'BONETA', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'BORDER', addressSystem: 'DELTA', priority: 0 },
        { name: 'BOTHWELL', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'BOTTLE HOLLOW', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'BOULDER', addressSystem: 'BOULDER', priority: 0 },
        { name: 'BOUNTIFUL', addressSystem: 'BOUNTIFUL', priority: 0 },
        { name: 'BOX ELDER COUNTY', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'BRIAN HEAD', addressSystem: 'BRIAN HEAD', priority: 1 },
        { name: 'BRIANHEAD', addressSystem: 'BRIAN HEAD', priority: 0 },
        { name: 'BRIDGELAND', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'BRIGHAM', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'BRIGHAM CITY', addressSystem: 'BRIGHAM CITY', priority: 1 },
        { name: 'BRIGHTON', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'BROOKSIDE', addressSystem: 'BROOKSIDE', priority: 0 },
        { name: 'BROWNS PARK', addressSystem: 'BROWNS PARK', priority: 0 },
        { name: 'BRYCE', addressSystem: 'BRYCE CANYON CITY', priority: 3 },
        { name: 'BRYCE CANYON', addressSystem: 'BRYCE CANYON CITY', priority: 2 },
        { name: 'BRYCE CANYON CITY', addressSystem: 'BRYCE CANYON CITY', priority: 1 },
        { name: 'BRYCE CANYON COUNTY', addressSystem: 'BRYCE CANYON COUNTY', priority: 5 },
        { name: 'BRYCE CYN CITY', addressSystem: 'BRYCE CANYON CITY', priority: 0 },
        { name: 'BRYCE CYN CNTY', addressSystem: 'BRYCE CANYON COUNTY', priority: 3 },
        { name: 'BRYCE CYN COUNTY', addressSystem: 'BRYCE CANYON COUNTY', priority: 4 },
        { name: 'BULLFROG', addressSystem: 'BULLFROG', priority: 0 },
        { name: 'BURMESTER', addressSystem: 'TOOELE', priority: 0 },
        { name: 'BURRVILLE', addressSystem: 'RICHFIELD', priority: 0 },
        { name: 'CACHE', addressSystem: 'LOGAN', priority: 1 },
        { name: 'CACHE COUNTY', addressSystem: 'LOGAN', priority: 0 },
        { name: 'CACHE JUNCTION', addressSystem: 'LOGAN', priority: 0 },
        { name: 'CAINEVILLE', addressSystem: 'CAINEVILLE', priority: 0 },
        { name: 'CALLAO', addressSystem: 'NEPHI', priority: 0 },
        { name: 'CAMP WILLIAMS', addressSystem: 'PROVO', priority: 0 },
        { name: 'CAMP WILLIAMS', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'CANNONVILLE', addressSystem: 'CANNONVILLE', priority: 0 },
        { name: 'CANYON MEADOWS', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'CANYON RIM', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'CARBON COUNTY', addressSystem: 'PRICE', priority: 0 },
        { name: 'CARBONVILLE', addressSystem: 'PRICE', priority: 0 },
        { name: 'CASTLE DALE', addressSystem: 'CASTLE DALE', priority: 1 },
        { name: 'CASTLE ROCK', addressSystem: 'HENEFER', priority: 0 },
        { name: 'CASTLE VALLEY', addressSystem: 'CASTLE VALLEY', priority: 0 },
        { name: 'CASTLEDALE', addressSystem: 'CASTLE DALE', priority: 0 },
        { name: 'CEDAR CITY', addressSystem: 'CEDAR CITY', priority: 0 },
        { name: 'CEDAR CREEK', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'CEDAR FORT', addressSystem: 'CEDAR FORT', priority: 0 },
        { name: 'CEDAR HILLS', addressSystem: 'PROVO', priority: 1 },
        { name: 'CEDAR HLS', addressSystem: 'PROVO', priority: 0 },
        { name: 'CEDAR SPRINGS', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'CEDAR VALLEY', addressSystem: 'CEDAR FORT', priority: 1 },
        { name: 'CENTER CREEK', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'CENTERFIELD', addressSystem: 'CENTERFIELD', priority: 0 },
        { name: 'CENTERVILLE', addressSystem: 'CENTERVILLE', priority: 0 },
        { name: 'CENTRAL', addressSystem: 'CENTRAL', priority: 0 },
        { name: 'CENTRAL VALLEY', addressSystem: 'CENTRAL VALLEY', priority: 0 },
        { name: 'CHARLESTON', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'CHESTER', addressSystem: 'MANTI', priority: 0 },
        { name: 'CIRCLEVILLE', addressSystem: 'CIRCLEVILLE', priority: 0 },
        { name: 'CISCO', addressSystem: 'MOAB', priority: 0 },
        { name: 'CLARKSTON', addressSystem: 'CLARKSTON', priority: 1 },
        { name: 'CLARKSTON', addressSystem: 'LOGAN', priority: 0 },
        { name: 'CLAWSON', addressSystem: 'CLAWSON', priority: 0 },
        { name: 'CLAY BASIN', addressSystem: 'CLAY BASIN', priority: 0 },
        { name: 'CLEAR CREEK', addressSystem: 'PRICE', priority: 0 },
        { name: 'CLEAR LAKE', addressSystem: 'DELTA', priority: 0 },
        { name: 'CLEARFIELD', addressSystem: 'CLEARFIELD', priority: 0 },
        { name: 'CLEVELAND', addressSystem: 'CLEVELAND', priority: 0 },
        { name: 'CLINTON', addressSystem: 'CLEARFIELD', priority: 0 },
        { name: 'CLIVE', addressSystem: 'TOOELE', priority: 0 },
        { name: 'CLOVER', addressSystem: 'RUSH VALLEY', priority: 0 },
        { name: 'COALVILLE', addressSystem: 'COALVILLE', priority: 0 },
        { name: 'COLLEGE WARD', addressSystem: 'LOGAN', priority: 0 },
        { name: 'COLLINSTON', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'COLOMBIA', addressSystem: 'EAST CARBON CITY', priority: 0 },
        { name: 'COLTON', addressSystem: 'PROVO', priority: 0 },
        { name: 'COPPERTON', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'CORINNE', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'CORNISH', addressSystem: 'LOGAN', priority: 0 },
        { name: 'COTTONWD HTS', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'COTTONWOOD HEIGHTS', addressSystem: 'SALT LAKE CITY', priority: 4 },
        { name: 'COTTONWOOD HEIGHTS CITY', addressSystem: 'SALT LAKE CITY', priority: 2 },
        { name: 'COTTONWOOD HGTS', addressSystem: 'SALT LAKE CITY', priority: 3 },
        { name: 'COTTONWOOD HTS', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'COVE', addressSystem: 'LOGAN', priority: 0 },
        { name: 'COVE FORT', addressSystem: 'KANOSH', priority: 0 },
        { name: 'COVERED BRIDGE', addressSystem: 'SPANISH FORK', priority: 0 },
        { name: 'CRESCENT JCT', addressSystem: 'GREEN RIVER', priority: 1 },
        { name: 'CRESCENT JUNCTION', addressSystem: 'GREEN RIVER', priority: 0 },
        { name: 'CROYDON', addressSystem: 'MORGAN', priority: 0 },
        { name: 'DAMMERON', addressSystem: 'DAMMERON VALLEY', priority: 0 },
        { name: 'DAMMERON VALLEY', addressSystem: 'DAMMERON VALLEY', priority: 2 },
        { name: 'DAMMERON VLY', addressSystem: 'DAMMERON VALLEY', priority: 1 },
        { name: 'DANIEL', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'DAVIS COUNTY', addressSystem: 'CLEARFIELD', priority: 0 },
        { name: 'DEEP CREEK', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'DEER CANYON', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'DEER CANYON PRESERVE', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'DEER CREST', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'DEER LODGE', addressSystem: 'DEER LODGE', priority: 0 },
        { name: 'DEER MOUNTAIN', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'DEER MTN', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'DEER VALLEY', addressSystem: 'PARK CITY', priority: 0 },
        { name: 'DELLE', addressSystem: 'GRANTSVILLE', priority: 0 },
        { name: 'DELLE', addressSystem: 'TOOELE', priority: 0 },
        { name: 'DELTA', addressSystem: 'DELTA', priority: 0 },
        { name: 'DESERET', addressSystem: 'DELTA', priority: 0 },
        { name: 'DESERT MOUND', addressSystem: 'CEDAR CITY', priority: 0 },
        { name: 'DEWEYVILLE', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'DIAMOND MOUNTAIN', addressSystem: 'DIAMOND MOUNTAIN', priority: 1 },
        { name: 'DIAMOND MOUNTAIN', addressSystem: 'VERNAL', priority: 1 },
        { name: 'DIAMOND MTN', addressSystem: 'DIAMOND MTN', priority: 0 },
        { name: 'DIAMOND MTN', addressSystem: 'VERNAL', priority: 0 },
        { name: 'DIVIDEND', addressSystem: 'PROVO', priority: 0 },
        { name: 'DRAPER', addressSystem: 'PROVO', priority: 0 },
        { name: 'DRAPER', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'DRY FORK', addressSystem: 'VERNAL', priority: 0 },
        { name: 'DUCHESNE', addressSystem: 'DUCHESNE', priority: 1 },
        { name: 'DUCHESNE', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'DUCHESNE COUNTY', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'DUCK CREEK VILLAGE', addressSystem: 'DUCK CREEK VILLAGE', priority: 1 },
        { name: 'DUCK CREEK VLG', addressSystem: 'DUCK CREEK VILLAGE', priority: 0 },
        { name: 'DUGWAY', addressSystem: 'DUGWAY', priority: 1 },
        { name: 'DUGWAY', addressSystem: 'TOOELE', priority: 0 },
        { name: 'DUTCH JOHN', addressSystem: 'DUTCH JOHN', priority: 0 },
        { name: 'EAGLE MOUNTAIN', addressSystem: 'EAGLE MOUNTAIN', priority: 3 },
        { name: 'EAGLE MOUNTAIN', addressSystem: 'PROVO', priority: 1 },
        { name: 'EAGLE MTN', addressSystem: 'EAGLE MOUNTAIN', priority: 2 },
        { name: 'EAGLE MTN', addressSystem: 'PROVO', priority: 0 },
        { name: 'EAST CARBON', addressSystem: 'EAST CARBON CITY', priority: 2 },
        { name: 'EAST CARBON CITY', addressSystem: 'EAST CARBON CITY', priority: 3 },
        { name: 'EAST CARBON SUNNYSIDE', addressSystem: 'EAST CARBON CITY', priority: 0 },
        { name: 'EAST LAYTON', addressSystem: 'LAYTON', priority: 0 },
        { name: 'EAST MILLCREEK', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'EASTLAND', addressSystem: 'MONTICELLO', priority: 0 },
        { name: 'ECHO', addressSystem: 'HENEFER', priority: 0 },
        { name: 'EDEN', addressSystem: 'OGDEN', priority: 0 },
        { name: 'ELBERTA', addressSystem: 'PROVO', priority: 0 },
        { name: 'ELK RIDGE', addressSystem: 'ELK RIDGE', priority: 1 },
        { name: 'ELK RIDGE', addressSystem: 'PROVO', priority: 0 },
        { name: 'ELMO', addressSystem: 'ELMO', priority: 0 },
        { name: 'ELSINORE', addressSystem: 'ELSINORE', priority: 0 },
        { name: 'ELWOOD', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'EMERY', addressSystem: 'EMERY', priority: 0 },
        { name: 'EMERY COUNTY', addressSystem: 'GREEN RIVER', priority: 0 },
        { name: 'EMIGRATION CANYON', addressSystem: 'SALT LAKE CITY', priority: 2 },
        { name: 'EMIGRATION CYN', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'EMIGRATN CYN', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'EMORY', addressSystem: 'HENEFER', priority: 0 },
        { name: 'ENOCH', addressSystem: 'CEDAR CITY', priority: 0 },
        { name: 'ENTERPRISE', addressSystem: 'ENTERPRISE', priority: 1 },
        { name: 'ENTERPRISE', addressSystem: 'MORGAN', priority: 0 },
        { name: 'EPHRAIM', addressSystem: 'EPHRAIM', priority: 1 },
        { name: 'EPHRAIM', addressSystem: 'MANTI', priority: 0 },
        { name: 'ERDA', addressSystem: 'TOOELE', priority: 0 },
        { name: 'ESCALANTE', addressSystem: 'ESCALANTE', priority: 0 },
        { name: 'ESKDALE', addressSystem: 'DELTA', priority: 0 },
        { name: 'ETNA', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'EUREKA', addressSystem: 'EUREKA', priority: 0 },
        { name: 'FAIRFIELD', addressSystem: 'PROVO', priority: 0 },
        { name: 'FAIRVIEW', addressSystem: 'FAIRVIEW', priority: 1 },
        { name: 'FAIRVIEW', addressSystem: 'MANTI', priority: 0 },
        { name: 'FARMINGTON', addressSystem: 'FARMINGTON', priority: 0 },
        { name: 'FARR WEST', addressSystem: 'OGDEN', priority: 0 },
        { name: 'FAUST', addressSystem: 'TOOELE', priority: 0 },
        { name: 'FAYETTE', addressSystem: 'FAYETTE', priority: 1 },
        { name: 'FAYETTE', addressSystem: 'NEPHI', priority: 0 },
        { name: 'FERRON', addressSystem: 'FERRON', priority: 0 },
        { name: 'FIELDING', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'FIELDING', addressSystem: 'FIELDING', priority: 1 },
        { name: 'FILLMORE', addressSystem: 'FILLMORE', priority: 0 },
        { name: 'FISH SPRINGS', addressSystem: 'SNAKE VALLEY', priority: 0 },
        { name: 'FISHLAKE', addressSystem: 'FISHLAKE', priority: 0 },
        { name: 'FLAMING GORGE', addressSystem: 'GREENDALE', priority: 0 },
        { name: 'FLOWELL', addressSystem: 'FILLMORE', priority: 0 },
        { name: 'FORT DOUGLAS', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'FORT DUCHESNE', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'FOUNTAIN GREEN', addressSystem: 'FOUNTAIN GREEN', priority: 3 },
        { name: 'FOUNTAIN GREEN', addressSystem: 'MANTI', priority: 1 },
        { name: 'FOUNTAIN GRN', addressSystem: 'FOUNTAIN GREEN', priority: 2 },
        { name: 'FOUNTAIN GRN', addressSystem: 'MANTI', priority: 0 },
        { name: 'FRANCIS', addressSystem: 'KAMAS', priority: 0 },
        { name: 'FREEDOM', addressSystem: 'MANTI', priority: 0 },
        { name: 'FREMONT', addressSystem: 'FREMONT', priority: 0 },
        { name: 'FREMONT JCT', addressSystem: 'FISHLAKE', priority: 1 },
        { name: 'FREMONT JUNCTION', addressSystem: 'FISHLAKE', priority: 0 },
        { name: 'FRUIT HEIGHTS', addressSystem: 'KAYSVILLE', priority: 0 },
        { name: 'FRUITA', addressSystem: 'FRUITA', priority: 0 },
        { name: 'FRUITLAND', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'FT DOUGLAS', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'GANDY', addressSystem: 'DELTA', priority: 0 },
        { name: 'GARDEN', addressSystem: 'GARDEN CITY', priority: 0 },
        { name: 'GARDEN CITY', addressSystem: 'GARDEN CITY', priority: 0 },
        { name: 'GARFIELD', addressSystem: 'BRYCE CANYON COUNTY', priority: 0 },
        { name: 'GARFIELD CO', addressSystem: 'BRYCE CANYON COUNTY', priority: 1 },
        { name: 'GARFIELD COUNTY', addressSystem: 'BRYCE CANYON COUNTY', priority: 2 },
        { name: 'GARLAND', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'GARLAND', addressSystem: 'GARLAND', priority: 1 },
        { name: 'GARRISON', addressSystem: 'DELTA', priority: 0 },
        { name: 'GENOLA', addressSystem: 'GENOLA', priority: 1 },
        { name: 'GENOLA', addressSystem: 'PROVO', priority: 0 },
        { name: 'GLENDALE', addressSystem: 'GLENDALE', priority: 0 },
        { name: 'GLENWOOD', addressSystem: 'GLENWOOD', priority: 0 },
        { name: 'GOLD HILL', addressSystem: 'TOOELE', priority: 0 },
        { name: 'GOSHEN', addressSystem: 'GOSHEN', priority: 1 },
        { name: 'GOSHEN', addressSystem: 'PROVO', priority: 0 },
        { name: 'GOSHUTE', addressSystem: 'SNAKE VALLEY', priority: 0 },
        { name: 'GRAND COUNTY', addressSystem: 'MOAB', priority: 0 },
        { name: 'GRANITE', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'GRANTSVILLE', addressSystem: 'GRANTSVILLE', priority: 1 },
        { name: 'GRANTSVILLE', addressSystem: 'TOOELE', priority: 0 },
        { name: 'GREEN RIVER', addressSystem: 'GREEN RIVER', priority: 0 },
        { name: 'GREENDALE', addressSystem: 'GREENDALE', priority: 0 },
        { name: 'GREENVILLE', addressSystem: 'BEAVER', priority: 0 },
        { name: 'GREENWICH', addressSystem: 'GREENWICH', priority: 0 },
        { name: 'GROUSE CREEK', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'GROVER', addressSystem: 'GROVER', priority: 0 },
        { name: 'GUNLOCK', addressSystem: 'GUNLOCK', priority: 0 },
        { name: 'GUNNISON', addressSystem: 'GUNNISON', priority: 1 },
        { name: 'GUNNISON', addressSystem: 'NEPHI', priority: 0 },
        { name: 'GUSHER', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'HAFB', addressSystem: 'HILL AIR FORCE BASE', priority: 0 },
        { name: 'HAILSTONE', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'HALCHITA', addressSystem: 'BLANDING', priority: 0 },
        { name: 'HALLS CROSSING', addressSystem: 'BLANDING', priority: 0 },
        { name: 'HAMILTONS FORT', addressSystem: 'CEDAR CITY', priority: 0 },
        { name: 'HAMLIN VALLEY', addressSystem: 'BERYL', priority: 0 },
        { name: 'HANKSVILLE', addressSystem: 'HANKSVILLE', priority: 0 },
        { name: 'HANNA', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'HARRISBURG', addressSystem: 'HURRICANE', priority: 0 },
        { name: 'HARRISVILLE', addressSystem: 'OGDEN', priority: 0 },
        { name: 'HATCH', addressSystem: 'HATCH', priority: 0 },
        { name: 'HATTON', addressSystem: 'FILLMORE', priority: 0 },
        { name: 'HAYDEN', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'HEBER', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'HEBER CITY', addressSystem: 'HEBER CITY', priority: 1 },
        { name: 'HELPER', addressSystem: 'HELPER', priority: 1 },
        { name: 'HELPER', addressSystem: 'PRICE', priority: 0 },
        { name: 'HENEFER', addressSystem: 'HENEFER', priority: 0 },
        { name: 'HENRIEVILLE', addressSystem: 'HENRIEVILLE', priority: 0 },
        { name: 'HERRIMAN', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'HIAWATHA', addressSystem: 'PRICE', priority: 0 },
        { name: 'HIDEOUT', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'HIGHLAND', addressSystem: 'PROVO', priority: 1 },
        { name: 'HIGHLAND', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'HILDALE', addressSystem: 'HILDALE', priority: 0 },
        { name: 'HILL AIR FORCE BASE', addressSystem: 'HILL AIR FORCE BASE', priority: 1 },
        { name: 'HINCKLEY', addressSystem: 'HINCKLEY', priority: 0 },
        { name: 'HITE', addressSystem: 'MONTICELLO', priority: 0 },
        { name: 'HOLDEN', addressSystem: 'HOLDEN', priority: 0 },
        { name: 'HOLLADAY', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'HONEYVILLE', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'HOOPER', addressSystem: 'OGDEN', priority: 0 },
        { name: 'HOWELL', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'HOYTSVILLE', addressSystem: 'COALVILLE', priority: 0 },
        { name: 'HUNTINGTON', addressSystem: 'HUNTINGTON', priority: 0 },
        { name: 'HUNTSVILLE', addressSystem: 'OGDEN', priority: 0 },
        { name: 'HURRICANE', addressSystem: 'HURRICANE', priority: 0 },
        { name: 'HYDE PARK', addressSystem: 'HYDE PARK', priority: 1 },
        { name: 'HYDE PARK', addressSystem: 'LOGAN', priority: 0 },
        { name: 'HYRUM', addressSystem: 'HYRUM', priority: 1 },
        { name: 'HYRUM', addressSystem: 'LOGAN', priority: 0 },
        { name: 'IBAPAH', addressSystem: 'IIBAPAH', priority: 0 },
        { name: 'INDEPENDENCE', addressSystem: 'HEBER CITY', priority: 1 },
        { name: 'INDEPENDENCE', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'INDEPENDENCE TOWN', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'INDIANOLA', addressSystem: 'MANTI', priority: 0 },
        { name: 'INTERLAKEN', addressSystem: 'MIDWAY', priority: 0 },
        { name: 'IOKA', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'IOSEPA', addressSystem: 'TOOELE', priority: 0 },
        { name: 'IRON COUNTY', addressSystem: 'CEDAR CITY', priority: 0 },
        { name: 'IRON SPRINGS', addressSystem: 'CEDAR CITY', priority: 0 },
        { name: 'IVINS', addressSystem: 'IVINS', priority: 0 },
        { name: 'JENSEN', addressSystem: 'VERNAL', priority: 0 },
        { name: 'JEREMY RANCH', addressSystem: 'PARK CITY', priority: 0 },
        { name: 'JERICHO JCT', addressSystem: 'NEPHI', priority: 0 },
        { name: 'JERICHO JUNCTION', addressSystem: 'NEPHI', priority: 1 },
        { name: 'JORDANELLE', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'JOSEPH', addressSystem: 'JOSEPH', priority: 0 },
        { name: 'JUAB COUNTY', addressSystem: 'NEPHI', priority: 0 },
        { name: 'JUNCTION', addressSystem: 'JUNCTION', priority: 0 },
        { name: 'KAMAS', addressSystem: 'KAMAS', priority: 0 },
        { name: 'KANAB', addressSystem: 'KANAB', priority: 0 },
        { name: 'KANARRAVILLE', addressSystem: 'KANARRAVILLE', priority: 0 },
        { name: 'KANE COUNTY', addressSystem: 'KANAB', priority: 0 },
        { name: 'KANESVILLE', addressSystem: 'OGDEN', priority: 0 },
        { name: 'KANOSH', addressSystem: 'FILLMORE', priority: 0 },
        { name: 'KANOSH', addressSystem: 'KANOSH', priority: 1 },
        { name: 'KAYSVILLE', addressSystem: 'KAYSVILLE', priority: 0 },
        { name: 'KEARNS', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'KEETLEY', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'KELTON', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'KENILWORTH', addressSystem: 'HELPER', priority: 0 },
        { name: 'KENILWORTH', addressSystem: 'PRICE', priority: 1 },
        { name: 'KIMBALL JCT', addressSystem: 'PARK CITY', priority: 0 },
        { name: 'KIMBALL JUNCTION', addressSystem: 'PARK CITY', priority: 1 },
        { name: 'KINGSTON', addressSystem: 'KINGSTON', priority: 0 },
        { name: 'KNOLLS', addressSystem: 'TOOELE', priority: 0 },
        { name: 'KOLOB', addressSystem: 'KOLOB', priority: 0 },
        { name: 'KOOSHAREM', addressSystem: 'KOOSHAREM', priority: 0 },
        { name: 'LA SAL', addressSystem: 'LA SAL', priority: 0 },
        { name: 'LA SAL JCT', addressSystem: 'LA SAL', priority: 1 },
        { name: 'LA SAL JUNCTION', addressSystem: 'LA SAL', priority: 0 },
        { name: 'LA VERKIN', addressSystem: 'LA VERKIN', priority: 0 },
        { name: 'LAKE POINT', addressSystem: 'TOOELE', priority: 0 },
        { name: 'LAKE SHORE', addressSystem: 'PROVO', priority: 0 },
        { name: 'LAKESIDE', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'LAKETOWN', addressSystem: 'LAKETOWN', priority: 0 },
        { name: 'LAKEVIEW', addressSystem: 'PROVO', priority: 0 },
        { name: 'LAPOINT', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'LAWRENCE', addressSystem: 'HUNTINGTON', priority: 0 },
        { name: 'LAYTON', addressSystem: 'LAYTON', priority: 0 },
        { name: 'LEAMINGTON', addressSystem: 'DELTA', priority: 0 },
        { name: 'LEAMINGTON', addressSystem: 'LEAMINGTON', priority: 1 },
        { name: 'LEEDS', addressSystem: 'LEEDS', priority: 0 },
        { name: 'LEETON', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'LEHI', addressSystem: 'LEHI', priority: 1 },
        { name: 'LEHI', addressSystem: 'PROVO', priority: 0 },
        { name: 'LEOTA', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'LEVAN', addressSystem: 'LEVAN', priority: 0 },
        { name: 'LEWISTON', addressSystem: 'LEWISTON', priority: 1 },
        { name: 'LEWISTON', addressSystem: 'LOGAN', priority: 0 },
        { name: 'LIBERTY', addressSystem: 'OGDEN', priority: 0 },
        { name: 'LINCOLN', addressSystem: 'TOOELE', priority: 0 },
        { name: 'LINDON', addressSystem: 'LINDON', priority: 1 },
        { name: 'LINDON', addressSystem: 'PROVO', priority: 0 },
        { name: 'LITTLE COTTONWOOD CANYON', addressSystem: 'SALT LAKE CITY', priority: 2 },
        { name: 'LITTLE COTTONWOOD CYN', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'LITTLETON', addressSystem: 'MORGAN', priority: 0 },
        { name: 'LLC', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'LOA', addressSystem: 'LOA', priority: 0 },
        { name: 'LOGAN', addressSystem: 'LOGAN', priority: 0 },
        { name: 'LONG VALLEY JCT', addressSystem: 'ALTON', priority: 2 },
        { name: 'LONG VALLEY JUNC', addressSystem: 'ALTON', priority: 0 },
        { name: 'LONG VALLEY JUNCTION', addressSystem: 'ALTON', priority: 1 },
        { name: 'LOW', addressSystem: 'TOOELE', priority: 0 },
        { name: 'LUCIN', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'LUND', addressSystem: 'CEDAR CITY', priority: 0 },
        { name: 'LYMAN', addressSystem: 'LYMAN', priority: 0 },
        { name: 'LYNN', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'LYNNDYL', addressSystem: 'LYNNDYL', priority: 0 },
        { name: 'MAESER', addressSystem: 'VERNAL', priority: 0 },
        { name: 'MAGNA', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'MAMMOTH', addressSystem: 'EUREKA', priority: 0 },
        { name: 'MAMMOTH CREEK', addressSystem: 'MAMMOTH CREEK', priority: 1 },
        { name: 'MAMMOTH CRK', addressSystem: 'MAMMOTH CREEK', priority: 0 },
        { name: 'MANDERFIELD', addressSystem: 'BEAVER', priority: 0 },
        { name: 'MANILA', addressSystem: 'MANILA', priority: 0 },
        { name: 'MANTI', addressSystem: 'MANTI', priority: 0 },
        { name: 'MANTUA', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'MANTUA', addressSystem: 'MANTUA', priority: 1 },
        { name: 'MAPLETON', addressSystem: 'MAPLETON', priority: 1 },
        { name: 'MAPLETON', addressSystem: 'PROVO', priority: 0 },
        { name: 'MARION', addressSystem: 'KAMAS', priority: 0 },
        { name: 'MARRIOTT', addressSystem: 'OGDEN', priority: 1 },
        { name: 'MARRIOTT SLATERVILLE', addressSystem: 'OGDEN', priority: 7 },
        { name: 'MARRIOTT-SLATERVILLE', addressSystem: 'OGDEN', priority: 6 },
        { name: 'MARRIOTT-SLATERVILLE CITY', addressSystem: 'OGDEN', priority: 5 },
        { name: 'MARYSVALE', addressSystem: 'MARYSVALE', priority: 0 },
        { name: 'MAYFIELD', addressSystem: 'MANTI', priority: 0 },
        { name: 'MAYFIELD', addressSystem: 'MAYFIELD', priority: 1 },
        { name: 'MEADOW', addressSystem: 'FILLLMORE', priority: 0 },
        { name: 'MEADOW', addressSystem: 'MEADOW', priority: 1 },
        { name: 'MEADOWVILLE', addressSystem: 'LAKETOWN', priority: 0 },
        { name: 'MENDON', addressSystem: 'LOGAN', priority: 0 },
        { name: 'MENDON', addressSystem: 'MENDON', priority: 1 },
        { name: 'MERCUR', addressSystem: 'TOOELE', priority: 0 },
        { name: 'MEXICAN HAT', addressSystem: 'BLANDING', priority: 0 },
        { name: 'MIDDLETON', addressSystem: 'ST GEORGE', priority: 0 },
        { name: 'MIDVALE', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'MIDWAY', addressSystem: 'MIDWAY', priority: 0 },
        { name: 'MILBURN', addressSystem: 'MANTI', priority: 0 },
        { name: 'MILFORD', addressSystem: 'MILFORD', priority: 0 },
        { name: 'MILLARD COUNTY', addressSystem: 'FILLMORE', priority: 0 },
        { name: 'MILLCREEK', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'MILLS', addressSystem: 'NEPHI', priority: 0 },
        { name: 'MILLS JCT', addressSystem: 'TOOELE', priority: 0 },
        { name: 'MILLS JUNCTION', addressSystem: 'TOOELE', priority: 1 },
        { name: 'MILLVILLE', addressSystem: 'LOGAN', priority: 0 },
        { name: 'MILLVILLE', addressSystem: 'MILLVILLE', priority: 1 },
        { name: 'MILTON', addressSystem: 'MORGAN', priority: 0 },
        { name: 'MINERSVILLE', addressSystem: 'MINERSVILLE', priority: 0 },
        { name: 'MOAB', addressSystem: 'MOAB', priority: 0 },
        { name: 'MODENA', addressSystem: 'MODENA', priority: 0 },
        { name: 'MOHRLAND', addressSystem: 'HUNTINGTON', priority: 0 },
        { name: 'MOLEN', addressSystem: 'FERRON', priority: 0 },
        { name: 'MONA', addressSystem: 'MONA', priority: 0 },
        { name: 'MONARCH', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'MONROE', addressSystem: 'MONROE', priority: 0 },
        { name: 'MONROE MOUNTAIN', addressSystem: 'MONROE MOUNTAIN', priority: 1 },
        { name: 'MONROE MTN', addressSystem: 'MONROE MOUNTAIN', priority: 0 },
        { name: 'MONTEZUMA CREEK', addressSystem: 'BLANDING', priority: 0 },
        { name: 'MONTICELLO', addressSystem: 'MONTICELLO', priority: 0 },
        { name: 'MONUMENT VALLEY', addressSystem: 'BLANDING', priority: 0 },
        { name: 'MOORE', addressSystem: 'EMERY', priority: 0 },
        { name: 'MORGAN', addressSystem: 'MORGAN', priority: 0 },
        { name: 'MORGAN COUNTY', addressSystem: 'MORGAN', priority: 0 },
        { name: 'MORONI', addressSystem: 'MANTI', priority: 0 },
        { name: 'MORONI', addressSystem: 'MORONI', priority: 1 },
        { name: 'MOSBY MOUNTAIN', addressSystem: 'ROOSEVELT', priority: 1 },
        { name: 'MOSBY MTN', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'MOUNT CARMEL', addressSystem: 'ORDERVILLE', priority: 0 },
        { name: 'MOUNT CARMEL JCT', addressSystem: 'ORDERVILLE', priority: 2 },
        { name: 'MOUNT CARMEL JUNCTION', addressSystem: 'ORDERVILLE', priority: 0 },
        { name: 'MOUNT OLYMPUS', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'MOUNT PLEASANT', addressSystem: 'MANTI', priority: 1 },
        { name: 'MOUNT PLEASANT', addressSystem: 'MOUNT PLEASANT', priority: 3 },
        { name: 'MOUNTAIN GREEN', addressSystem: 'MORGAN', priority: 1 },
        { name: 'MOUNTAIN HOME', addressSystem: 'ROOSEVELT', priority: 1 },
        { name: 'MRIOTT SLTRVL', addressSystem: 'OGDEN', priority: 4 },
        { name: 'MS CITY', addressSystem: 'OGDEN', priority: 3 },
        { name: 'MSC', addressSystem: 'OGDEN', priority: 2 },
        { name: 'MT CARMEL', addressSystem: 'ORDERVILLE', priority: 1 },
        { name: 'MT CARMEL JCT', addressSystem: 'ORDERVILLE', priority: 1 },
        { name: 'MT OLYMPUS', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'MT PLEASANT', addressSystem: 'MANTI', priority: 0 },
        { name: 'MT PLEASANT', addressSystem: 'MOUNT PLEASANT', priority: 2 },
        { name: 'MTN GREEN', addressSystem: 'MORGAN', priority: 0 },
        { name: 'MTN HOME', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'MURRAY', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'MYTON', addressSystem: 'MYTON', priority: 1 },
        { name: 'MYTON', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'N LOGAN', addressSystem: 'LOGAN', priority: 0 },
        { name: 'N SNYDERVILLE BASIN', addressSystem: 'PARK CITY', priority: 0 },
        { name: 'NAME', addressSystem: 'GRID_NAME', priority: 0 },
        { name: 'NAPLES', addressSystem: 'VERNAL', priority: 0 },
        { name: 'NATURAL BRIDGES', addressSystem: 'BLANDING', priority: 0 },
        { name: 'NATURAL BRIDGES NM', addressSystem: 'BLANDING', priority: 0 },
        { name: 'NAVAJO MOUNTAIN', addressSystem: 'BLANDING', priority: 1 },
        { name: 'NAVAJO MTN', addressSystem: 'BLANDING', priority: 0 },
        { name: 'NEOLA', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'NEPHI', addressSystem: 'NEPHI', priority: 0 },
        { name: 'NEW HARMONY', addressSystem: 'NEW HARMONY', priority: 0 },
        { name: 'NEWCASTLE', addressSystem: 'NEWCASTLE', priority: 0 },
        { name: 'NEWTON', addressSystem: 'LOGAN', priority: 0 },
        { name: 'NEWTON', addressSystem: 'NEWTON', priority: 1 },
        { name: 'NIBLEY', addressSystem: 'LOGAN', priority: 0 },
        { name: 'NORTH LOGAN', addressSystem: 'LOGAN', priority: 1 },
        { name: 'NORTH OGDEN', addressSystem: 'OGDEN', priority: 0 },
        { name: 'NORTH SALT LAKE', addressSystem: 'NSL', priority: 1 },
        { name: 'NORTH SNYDERVILLE BASIN', addressSystem: 'PARK CITY', priority: 1 },
        { name: 'NOTOM', addressSystem: 'NOTOM', priority: 0 },
        { name: 'NSL', addressSystem: 'NSL', priority: 0 },
        { name: 'OAK CITY', addressSystem: 'OAK CITY', priority: 0 },
        { name: 'OAK CREEK', addressSystem: 'MANTI', priority: 0 },
        { name: 'OAKLEY', addressSystem: 'KAMAS', priority: 0 },
        { name: 'OAKS PARK RES', addressSystem: 'VERNAL', priority: 0 },
        { name: 'OAKS PARK RESERVOIR', addressSystem: 'VERNAL', priority: 1 },
        { name: 'OASIS', addressSystem: 'DELTA', priority: 0 },
        { name: 'OGDEN', addressSystem: 'OGDEN', priority: 0 },
        { name: 'OLD FISHLAKE', addressSystem: 'OLD FISHLAKE', priority: 0 },
        { name: 'OLD LA SAL', addressSystem: 'LA SAL', priority: 0 },
        { name: 'OLJATO', addressSystem: 'BLANDING', priority: 0 },
        { name: 'OPHIR', addressSystem: 'TOOELE', priority: 0 },
        { name: 'ORANGEVILLE', addressSystem: 'ORANGEVILLE', priority: 0 },
        { name: 'ORDERVILLE', addressSystem: 'ORDERVILLE', priority: 0 },
        { name: 'OREM', addressSystem: 'OREM', priority: 1 },
        { name: 'OREM', addressSystem: 'PROVO', priority: 0 },
        { name: 'OSIRIS', addressSystem: 'ANTIMONY', priority: 0 },
        { name: 'OTTER CREEK', addressSystem: 'OTTER CREEK', priority: 0 },
        { name: 'OURAY', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'PALMYRA', addressSystem: 'PROVO', priority: 0 },
        { name: 'PANGUITCH', addressSystem: 'PANGUITCH', priority: 0 },
        { name: 'PANGUITCH LAKE', addressSystem: 'PANGUITCH LAKE', priority: 0 },
        { name: 'PARADISE', addressSystem: 'LOGAN', priority: 0 },
        { name: 'PARAGONAH', addressSystem: 'PARAGONAH', priority: 0 },
        { name: 'PARK CITY', addressSystem: 'PARK CITY', priority: 1 },
        { name: 'PARK VALLEY', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'PAROWAN', addressSystem: 'PAROWAN', priority: 0 },
        { name: 'PAYSON', addressSystem: 'PAYSON', priority: 1 },
        { name: 'PAYSON', addressSystem: 'PROVO', priority: 0 },
        { name: 'PC', addressSystem: 'PARK CITY', priority: 0 },
        { name: 'PENROSE', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'PEOA', addressSystem: 'KAMAS', priority: 0 },
        { name: 'PERRY', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'PETER', addressSystem: 'LOGAN', priority: 0 },
        { name: 'PETERSON', addressSystem: 'MORGAN', priority: 0 },
        { name: 'PICKLEVILLE', addressSystem: 'GARDEN CITY', priority: 0 },
        { name: 'PIGEON HOLLOW JCT', addressSystem: 'MANTI', priority: 1 },
        { name: 'PIGEON HOLLOW JUNCTION', addressSystem: 'MANTI', priority: 0 },
        { name: 'PINE VALLEY', addressSystem: 'PINE VALLEY', priority: 0 },
        { name: 'PINTO', addressSystem: 'PINTO', priority: 0 },
        { name: 'PLAIN CITY', addressSystem: 'OGDEN', priority: 0 },
        { name: 'PLEASANT GROVE', addressSystem: 'PLEASANT GROVE', priority: 3 },
        { name: 'PLEASANT GROVE', addressSystem: 'PROVO', priority: 1 },
        { name: 'PLEASANT GRV', addressSystem: 'PLEASANT GROVE', priority: 2 },
        { name: 'PLEASANT GRV', addressSystem: 'PROVO', priority: 0 },
        { name: 'PLEASANT VIEW', addressSystem: 'OGDEN', priority: 0 },
        { name: 'PLYMOUTH', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'PORTAGE', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'PORTERVILLE', addressSystem: 'MORGAN', priority: 0 },
        { name: 'PRICE', addressSystem: 'PRICE', priority: 0 },
        { name: 'PROMONTORY', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'PROVIDENCE', addressSystem: 'LOGAN', priority: 0 },
        { name: 'PROVIDENCE', addressSystem: 'PROVIDENCE', priority: 1 },
        { name: 'PROVO', addressSystem: 'PROVO', priority: 0 },
        { name: 'RANDLETT', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'RANDOLPH', addressSystem: 'RANDOLPH', priority: 0 },
        { name: 'REDMOND', addressSystem: 'REDMOND', priority: 0 },
        { name: 'RICHFIELD', addressSystem: 'RICHFIELD', priority: 0 },
        { name: 'RICHMOND', addressSystem: 'LOGAN', priority: 0 },
        { name: 'RICHMOND', addressSystem: 'RICHMOND', priority: 1 },
        { name: 'RICHVILLE', addressSystem: 'MORGAN', priority: 0 },
        { name: 'RIVER HEIGHTS', addressSystem: 'LOGAN', priority: 0 },
        { name: 'RIVERDALE', addressSystem: 'OGDEN', priority: 0 },
        { name: 'RIVERSIDE', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'RIVERTON', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'ROCKVILLE', addressSystem: 'ROCKVILLE', priority: 1 },
        { name: 'ROCKY RIDGE', addressSystem: 'MONA', priority: 0 },
        { name: 'ROOSEVELT', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'ROSETTE', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'ROUND VALLEY', addressSystem: 'LAKETOWN', priority: 0 },
        { name: 'ROWLEY', addressSystem: 'TOOELE', priority: 0 },
        { name: 'ROWLEY JCT', addressSystem: 'TOOELE', priority: 1 },
        { name: 'ROWLEY JUNCTION', addressSystem: 'TOOELE', priority: 0 },
        { name: 'ROY', addressSystem: 'OGDEN', priority: 0 },
        { name: 'RUSH VALLEY', addressSystem: 'RUSH VALLEY', priority: 1 },
        { name: 'RUSH VALLEY', addressSystem: 'TOOELE', priority: 0 },
        { name: 'SAGE CREEK JCT', addressSystem: 'RANDOLPH', priority: 1 },
        { name: 'SAGE CREEK JUNCTION', addressSystem: 'RANDOLPH', priority: 0 },
        { name: 'SAINT GEORGE', addressSystem: 'ST GEORGE', priority: 0 },
        { name: 'SALEM', addressSystem: 'PROVO', priority: 0 },
        { name: 'SALEM', addressSystem: 'SALEM', priority: 1 },
        { name: 'SALINA', addressSystem: 'SALINA', priority: 0 },
        { name: 'SALT LAKE', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'SALT LAKE CITY', addressSystem: 'SALT LAKE CITY', priority: 2 },
        { name: 'SALT LAKE CNTY', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'SALT LAKE CO', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'SALT LAKE COUNTY', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'SALT SPRINGS', addressSystem: 'TOOELE', priority: 0 },
        { name: 'SAMAK', addressSystem: 'KAMAS', priority: 0 },
        { name: 'SAN JUAN COUNTY', addressSystem: 'MONTICELLO', priority: 0 },
        { name: 'SANDY', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'SANDY RANCH', addressSystem: 'SANDY RANCH', priority: 0 },
        { name: 'SANPETE COUNTY', addressSystem: 'MANTI', priority: 0 },
        { name: 'SANTA CLARA', addressSystem: 'SANTA CLARA', priority: 0 },
        { name: 'SANTAQUIN', addressSystem: 'PROVO', priority: 0 },
        { name: 'SANTAQUIN', addressSystem: 'SANTAQUIN', priority: 1 },
        { name: 'SARATOGA SPGS', addressSystem: 'PROVO', priority: 0 },
        { name: 'SARATOGA SPGS', addressSystem: 'SARATOGA SPRINGS', priority: 2 },
        { name: 'SARATOGA SPRINGS', addressSystem: 'PROVO', priority: 1 },
        { name: 'SARATOGA SPRINGS', addressSystem: 'SARATOGA SPRINGS', priority: 3 },
        { name: 'SCIPIO', addressSystem: 'FILLMORE', priority: 0 },
        { name: 'SCIPIO', addressSystem: 'SCIPIO', priority: 1 },
        { name: 'SCOFIELD', addressSystem: 'PRICE', priority: 0 },
        { name: 'SCOFIELD', addressSystem: 'SCOFIELD', priority: 1 },
        { name: 'SEVIER', addressSystem: 'SEVIER', priority: 0 },
        { name: 'SGU', addressSystem: 'ST GEORGE', priority: 0 },
        { name: 'SHIVWITS', addressSystem: 'ST GEORGE', priority: 0 },
        { name: 'SIGURD', addressSystem: 'SIGURD', priority: 0 },
        { name: 'SILVER CITY', addressSystem: 'EUREKA', priority: 0 },
        { name: 'SILVER CREEK JUNCTION', addressSystem: 'PARK CITY', priority: 0 },
        { name: 'SILVER REEF', addressSystem: 'LEEDS', priority: 0 },
        { name: 'SILVER SUMMIT', addressSystem: 'PARK CITY', priority: 0 },
        { name: 'SJ', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'SL CI', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'SLATERVILLE', addressSystem: 'OGDEN', priority: 0 },
        { name: 'SLC', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'SLCO', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'SMITHFIELD', addressSystem: 'LOGAN', priority: 0 },
        { name: 'SMITHFIELD', addressSystem: 'SMITHFIELD', priority: 1 },
        { name: 'SNAKE VALLEY', addressSystem: 'SNAKE VALLEY', priority: 0 },
        { name: 'SNOW BASIN', addressSystem: 'OGDEN', priority: 0 },
        { name: 'SNOWVILLE', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'SNOWVILLE', addressSystem: 'SNOWVILLE', priority: 1 },
        { name: 'SNYDERVILLE', addressSystem: 'PARK CITY', priority: 0 },
        { name: 'SO SALT LAKE', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'SOLDIER SUMMIT', addressSystem: 'SOLDIER SUMMIT', priority: 0 },
        { name: 'SOLITUDE', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'SOUTH JORDAN', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'SOUTH OGDEN', addressSystem: 'OGDEN', priority: 0 },
        { name: 'SOUTH SALT LAKE', addressSystem: 'SALT LAKE CITY', priority: 2 },
        { name: 'SOUTH SNYDERVILLE BASIN', addressSystem: 'PARK CITY', priority: 0 },
        { name: 'SOUTH WEBER', addressSystem: 'OGDEN', priority: 0 },
        { name: 'SOUTH WILLARD', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'SPANISH FORK', addressSystem: 'PROVO', priority: 0 },
        { name: 'SPANISH FORK', addressSystem: 'SPANISH FORK', priority: 1 },
        { name: 'SPANISH VALLEY', addressSystem: 'MONTICELLO', priority: 0 },
        { name: 'SPIRIT LAKE', addressSystem: 'SPIRIT LAKE', priority: 0 },
        { name: 'SPRING CITY', addressSystem: 'MANTI', priority: 0 },
        { name: 'SPRING CITY', addressSystem: 'SPRING CITY', priority: 1 },
        { name: 'SPRING GLEN', addressSystem: 'HELPER', priority: 0 },
        { name: 'SPRING LAKE', addressSystem: 'PROVO', priority: 0 },
        { name: 'SPRINGDALE', addressSystem: 'SPRINGDALE', priority: 0 },
        { name: 'SPRINGVILLE', addressSystem: 'PROVO', priority: 0 },
        { name: 'SPRINGVILLE', addressSystem: 'SPRINGVILLE', priority: 1 },
        { name: 'SPRY', addressSystem: 'PANGUITCH', priority: 0 },
        { name: 'SSL', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'ST GEORGE', addressSystem: 'ST GEORGE', priority: 1 },
        { name: 'ST. GEORGE', addressSystem: 'ST GEORGE', priority: 0 },
        { name: 'STANDARDVILLE', addressSystem: 'PRICE', priority: 0 },
        { name: 'STANDROD', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'STANSBURY PARK', addressSystem: 'TOOELE', priority: 0 },
        { name: 'STERLING', addressSystem: 'MANTI', priority: 0 },
        { name: 'STERLING', addressSystem: 'STERLING', priority: 1 },
        { name: 'STG', addressSystem: 'ST GEORGE', priority: 0 },
        { name: 'STOCKTON', addressSystem: 'STOCKTON', priority: 0 },
        { name: 'STOCKTON', addressSystem: 'TOOELE', priority: 0 },
        { name: 'STODDARD', addressSystem: 'MORGAN', priority: 0 },
        { name: 'STRAWBERRY', addressSystem: 'STRAWBERRY', priority: 0 },
        { name: 'SUGARVILLE', addressSystem: 'DELTA', priority: 0 },
        { name: 'SUMMIT', addressSystem: 'SUMMIT', priority: 0 },
        { name: 'SUMMIT COUNTY', addressSystem: 'KAMAS', priority: 0 },
        { name: 'SUMMIT PARK', addressSystem: 'PARK CITY', priority: 0 },
        { name: 'SUNDANCE', addressSystem: 'PROVO', priority: 0 },
        { name: 'SUNNYSIDE', addressSystem: 'EAST CARBON CITY', priority: 1 },
        { name: 'SUNNYSIDE', addressSystem: 'PRICE', priority: 0 },
        { name: 'SUNSET', addressSystem: 'CLEARFIELD', priority: 0 },
        { name: 'SUTHERLAND', addressSystem: 'DELTA', priority: 0 },
        { name: 'SYRACUSE', addressSystem: 'CLEARFIELD', priority: 0 },
        { name: 'TABIONA', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'TALMAGE', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'TAYLOR', addressSystem: 'OGDEN', priority: 0 },
        { name: 'TAYLORS FLAT', addressSystem: 'BROWNS PARK', priority: 0 },
        { name: 'TAYLORSVILLE', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'TEASDALE', addressSystem: 'TEASDALE', priority: 0 },
        { name: 'TERRA', addressSystem: 'TOOELE', priority: 0 },
        { name: 'THATCHER', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'THISTLE', addressSystem: 'PROVO', priority: 0 },
        { name: 'THOMPSON', addressSystem: 'THOMPSON SPRINGS', priority: 1 },
        { name: 'THOMPSON SPRINGS', addressSystem: 'THOMPSON SPRINGS', priority: 0 },
        { name: 'TICABOO', addressSystem: 'TICABOO', priority: 0 },
        { name: 'TIMBER LAKES', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'TINTIC', addressSystem: 'EUREKA', priority: 0 },
        { name: 'TOOELE', addressSystem: 'TOOELE', priority: 0 },
        { name: 'TOOELE ARMY DEPOT', addressSystem: 'TOOELE', priority: 0 },
        { name: 'TOOELE COUNTY', addressSystem: 'TOOELE', priority: 0 },
        { name: 'TOOELE COUNTY', addressSystem: 'TOOELE', priority: 0 },
        { name: 'TOPAZ', addressSystem: 'DELTA', priority: 0 },
        { name: 'TOQUERVILLE', addressSystem: 'TOQUERVILLE', priority: 0 },
        { name: 'TORREY', addressSystem: 'TORREY', priority: 0 },
        { name: 'TREMONTON', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'TREMONTON', addressSystem: 'TREMONTON', priority: 1 },
        { name: 'TRENTON', addressSystem: 'LOGAN', priority: 0 },
        { name: 'TRENTON', addressSystem: 'TRENTON', priority: 1 },
        { name: 'TRIDELL', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'TROPIC', addressSystem: 'TROPIC', priority: 0 },
        { name: 'TROUT CREEK', addressSystem: 'NEPHI', priority: 0 },
        { name: 'TROUT CREEK', addressSystem: 'SNAKE VALLEY', priority: 1 },
        { name: 'TSELAKAI DEZZA', addressSystem: 'BLANDING', priority: 0 },
        { name: 'TUHAYE', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'UCOLO', addressSystem: 'MONTICELLO', priority: 0 },
        { name: 'UINIVERSITY OF UTAH', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'UINTAH', addressSystem: 'OGDEN', priority: 0 },
        { name: 'UINTAH COUNTY', addressSystem: 'VERNAL', priority: 0 },
        { name: 'UPALCO', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'UTAH COUNTY', addressSystem: 'PROVO', priority: 0 },
        { name: 'VENICE', addressSystem: 'VENICE', priority: 0 },
        { name: 'VERNAL', addressSystem: 'VERNAL', priority: 0 },
        { name: 'VERNON', addressSystem: 'TOOELE', priority: 0 },
        { name: 'VERNON', addressSystem: 'VERNON', priority: 1 },
        { name: 'VEYO', addressSystem: 'VEYO', priority: 0 },
        { name: 'VICTORY RANCH', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'VINEYARD', addressSystem: 'PROVO', priority: 0 },
        { name: 'VINEYARD', addressSystem: 'VINEYARD', priority: 1 },
        { name: 'VIRGIN', addressSystem: 'VIRGIN', priority: 0 },
        { name: 'W BOUNTIFUL', addressSystem: 'BOUNTIFUL', priority: 0 },
        { name: 'WAHSATCH', addressSystem: 'HENEFER', priority: 0 },
        { name: 'WALES', addressSystem: 'MANTI', priority: 0 },
        { name: 'WALES', addressSystem: 'WALES', priority: 1 },
        { name: 'WALLSBURG', addressSystem: 'WALLSBURG', priority: 0 },
        { name: 'WANSHIP', addressSystem: 'WANSHIP', priority: 0 },
        { name: 'WARREN', addressSystem: 'OGDEN', priority: 0 },
        { name: 'WASATCH COUNTY', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'WASHAKIE', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'WASHINGTON', addressSystem: 'WASHINGTON', priority: 1 },
        { name: 'WASHINGTON CITY', addressSystem: 'WASHINGTON', priority: 0 },
        { name: 'WASHINGTON TERRACE', addressSystem: 'OGDEN', priority: 0 },
        { name: 'WATTIS', addressSystem: 'PRICE', priority: 0 },
        { name: 'WEBER COUNTY', addressSystem: 'OGDEN', priority: 0 },
        { name: 'WELLINGTON', addressSystem: 'PRICE', priority: 0 },
        { name: 'WELLINGTON', addressSystem: 'WELLINGTON', priority: 1 },
        { name: 'WELLSVILLE', addressSystem: 'LOGAN', priority: 0 },
        { name: 'WELLSVILLE', addressSystem: 'WELLSVILLE', priority: 1 },
        { name: 'WENDOVER', addressSystem: 'TOOELE', priority: 0 },
        { name: 'WENDOVER', addressSystem: 'WENDOVER', priority: 1 },
        { name: 'WEST BOUNTIFUL', addressSystem: 'BOUNTIFUL', priority: 0 },
        { name: 'WEST HAVEN', addressSystem: 'OGDEN', priority: 0 },
        { name: 'WEST JORDAN', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'WEST MOUNTAIN', addressSystem: 'PROVO', priority: 0 },
        { name: 'WEST POINT', addressSystem: 'CLEARFIELD', priority: 0 },
        { name: 'WEST VALLEY', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'WEST VALLEY CITY', addressSystem: 'SALT LAKE CITY', priority: 1 },
        { name: 'WEST WAREN', addressSystem: 'OGDEN', priority: 0 },
        { name: 'WEST WOOD', addressSystem: 'PRICE', priority: 0 },
        { name: 'WESTWATER', addressSystem: 'MOAB', priority: 0 },
        { name: 'WHEELON', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'WHITE CITY', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'WHITE MESA', addressSystem: 'BLANDING', priority: 0 },
        { name: 'WHITEROCKS', addressSystem: 'ROOSEVELT', priority: 0 },
        { name: 'WIDTSOE', addressSystem: 'WIDTSOE', priority: 0 },
        { name: 'WIDTSOE JCT', addressSystem: 'WIDTSOE', priority: 1 },
        { name: 'WIDTSOE JUNCTION', addressSystem: 'WIDTSOE', priority: 0 },
        { name: 'WILLARD', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'WILLARD', addressSystem: 'WILLARD', priority: 1 },
        { name: 'WJ', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'WOLF CREEK', addressSystem: 'OGDEN', priority: 0 },
        { name: 'WOLF CREEK RANCH', addressSystem: 'HEBER CITY', priority: 0 },
        { name: 'WOODLAND', addressSystem: 'WOODLAND', priority: 0 },
        { name: 'WOODLAND HILLS', addressSystem: 'PROVO', priority: 1 },
        { name: 'WOODLAND HILLS', addressSystem: 'WOODLAND HILLS', priority: 1 },
        { name: 'WOODLAND HLS', addressSystem: 'PROVO', priority: 0 },
        { name: 'WOODLAND HLS', addressSystem: 'WOODLAND HILLS', priority: 0 },
        { name: 'WOODROW', addressSystem: 'DELTA', priority: 0 },
        { name: 'WOODRUFF', addressSystem: 'WOODRUFF', priority: 0 },
        { name: 'WOODS CROSS', addressSystem: 'BOUNTIFUL', priority: 0 },
        { name: 'WVC', addressSystem: 'SALT LAKE CITY', priority: 0 },
        { name: 'YOST', addressSystem: 'BRIGHAM CITY', priority: 0 },
        { name: 'ZION NATIONAL PARK', addressSystem: 'KOLOB', priority: 1 },
        { name: 'ZION NATIONAL PARK', addressSystem: 'NEW HARMONY', priority: 1 },
        { name: 'ZION NATIONAL PARK', addressSystem: 'ROCKVILLE', priority: 0 },
        { name: 'ZION NATIONAL PARK', addressSystem: 'SPRINGDALE', priority: 1 },
        { name: 'ZION NATIONAL PARK', addressSystem: 'VIRGIN', priority: 1 },
        { name: 'ZION NTL PARK', addressSystem: 'KOLOB', priority: 0 },
        { name: 'ZION NTL PARK', addressSystem: 'NEW HARMONY', priority: 0 },
        { name: 'ZION NTL PARK', addressSystem: 'ROCKVILLE', priority: 0 },
        { name: 'ZION NTL PARK', addressSystem: 'SPRINGDALE', priority: 0 },
        { name: 'ZION NTL PARK', addressSystem: 'VIRGIN', priority: 0 }
    ];
});
